import { defineArrayMember, defineField, defineType } from "sanity";

const imageFields = [
  defineField({
    name: "alt",
    title: "Alternative text",
    type: "string",
    description: "Describe the image for accessibility and search engines.",
    validation: (rule) => rule.required().min(8).max(180),
  }),
  defineField({
    name: "position",
    title: "Image position",
    type: "string",
    description: "Optional CSS object-position value, for example: center 40%.",
    initialValue: "center",
    validation: (rule) => rule.max(40),
  }),
];

export const projectType = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "content", title: "Project content", default: true },
    { name: "media", title: "Images" },
    { name: "publishing", title: "Publishing" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Project title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().min(3).max(120),
    }),
    defineField({
      name: "slug",
      title: "URL slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "shortTitle",
      title: "Short title",
      type: "string",
      group: "content",
      description: "A shorter label for compact cards and image placeholders.",
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: "sector",
      title: "Sector",
      type: "reference",
      group: "content",
      to: [{ type: "sector" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "projectType",
      title: "Project type",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: "role",
      title: "Quantum's role",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().max(140),
    }),
    defineField({
      name: "summary",
      title: "Project summary",
      type: "text",
      rows: 3,
      group: "content",
      description: "Used on project cards and at the top of the project page.",
      validation: (rule) => rule.required().min(30).max(220),
    }),
    defineField({
      name: "scope",
      title: "Project scope",
      type: "text",
      rows: 7,
      group: "content",
      validation: (rule) => rule.required().min(60).max(1200),
    }),
    defineField({
      name: "services",
      title: "Services provided",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      validation: (rule) => rule.required().min(1).max(8).unique(),
    }),
    defineField({
      name: "coverImage",
      title: "Cover image",
      type: "image",
      group: "media",
      options: { hotspot: true },
      fields: imageFields,
      validation: (rule) => rule.required().warning("Add a cover image before featuring this project."),
    }),
    defineField({
      name: "gallery",
      title: "Project gallery",
      type: "array",
      group: "media",
      of: [
        defineArrayMember({
          name: "projectImage",
          title: "Project image",
          type: "image",
          options: { hotspot: true },
          fields: imageFields,
        }),
      ],
      validation: (rule) => rule.max(16),
    }),
    defineField({
      name: "featured",
      title: "Feature on homepage",
      type: "boolean",
      group: "publishing",
      initialValue: false,
    }),
    defineField({
      name: "featuredOrder",
      title: "Homepage order",
      type: "number",
      group: "publishing",
      description: "1 is the large lead project; 2 and 3 are the smaller cards.",
      hidden: ({ document }) => !document?.featured,
      validation: (rule) => rule.integer().min(1).max(99),
    }),
    defineField({
      name: "displayOrder",
      title: "Portfolio order",
      type: "number",
      group: "publishing",
      initialValue: 100,
      validation: (rule) => rule.required().integer().min(0),
    }),
    defineField({
      name: "tone",
      title: "Placeholder colour",
      type: "string",
      group: "publishing",
      description: "Used only if an image is temporarily unavailable.",
      initialValue: "blue",
      options: {
        list: [
          { title: "Blue", value: "blue" },
          { title: "Steel", value: "steel" },
          { title: "Amber", value: "amber" },
          { title: "Night", value: "night" },
          { title: "Green", value: "green" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "publishedAt",
      title: "Original publication date",
      type: "datetime",
      group: "publishing",
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: "seoTitle",
      title: "SEO title",
      type: "string",
      group: "seo",
      description: "Optional. The project title is used when this is empty.",
      validation: (rule) => rule.max(65),
    }),
    defineField({
      name: "seoDescription",
      title: "SEO description",
      type: "text",
      rows: 3,
      group: "seo",
      description: "Optional. The project summary is used when this is empty.",
      validation: (rule) => rule.max(170),
    }),
  ],
  orderings: [
    {
      title: "Portfolio order",
      name: "portfolioOrder",
      by: [{ field: "displayOrder", direction: "asc" }, { field: "title", direction: "asc" }],
    },
    {
      title: "Newest first",
      name: "newestFirst",
      by: [{ field: "publishedAt", direction: "desc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      sector: "sector.name",
      location: "location",
      media: "coverImage",
    },
    prepare({ title, sector, location, media }) {
      return {
        title,
        subtitle: [sector, location].filter(Boolean).join(" · "),
        media,
      };
    },
  },
});
